ADS integration and unit testing (mocking + developing)
HyperLEDA/db-app pull request #126
Opened 2024-04-29 13:02 UTC by azzzile

2024-04-29 13:53 UTC, Kraysent requested changes

2024-04-29 13:53 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +from astroquery import nasa_ads as na
давай лучше ads вместо na, лучше читаться будет

2024-04-29 13:53 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                r.title, r.authors, r.year = publication["title"][0], list(publication["author"]), int(r.bibcode[:4])
`int(r.bibcode[:4])`
а ads не возвращает поля с годом?

2024-04-29 13:53 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                pass
уже говорили, тут 400 можно вернуть

2024-04-29 13:53 UTC, Kraysent commented on app/presentation/commands/runserver/start.py
> +                raise Exception(f"Environment variable {variable} is not set")
Использование голого exception - не очень хороший тон
Тут лучше какой-нибудь RuntimeError

2024-04-29 13:53 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                na.ADS.TOKEN = os.environ.get("ADS_TOKEN")
Давай здесь работать не с глобальным классом ADS, а с его инстансом
Что-то в духе 
```
ads_client = ads.ADSClass()
```
и дальше с ним работать точно так же как работаешь с глобальным.

У нас запросы потенциально могут исполняться параллельно, поэтому если работать с глобальным инстансом класса, у нас может возникнуть data race, когда две параллельно исполняющиеся функции одновременно записывают в одно место, это не оч хорошо

2024-04-29 13:54 UTC, azzzile commented on app/domain/usecases/__init__.py
> +from astroquery import nasa_ads as na
ок, поправим!

это в новую ветку коммитить?

2024-04-29 13:55 UTC, azzzile commented on app/domain/usecases/__init__.py
> +                pass
дадада это я еще не пофиксила

2024-04-29 13:55 UTC, azzzile commented on app/presentation/commands/runserver/start.py
> +                raise Exception(f"Environment variable {variable} is not set")
пон!

2024-04-29 13:58 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                r.title, r.authors, r.year = publication["title"][0], list(publication["author"]), int(r.bibcode[:4])
не оч хочется на вид bibcode завязываться, это а) хуже читается б) берется не из предназначенного для этого поля, а неявным образом вытаскивается из какого-то другого поля
если есть pubdate, лучше его использовать, явное лучше неявного)

2024-04-29 13:58 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +from astroquery import nasa_ads as na
в ту же всё, эта ветка актуальа до вливания в мастер

2024-05-08 14:12 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                    int(publication["pubdate"][:4]),
а он в каком виде приходит? если это какая-то читаемая дата, то лучше при помощи `datetime.strptime` парсить и потом делать `datetime.year`, `[:4]` всё ещё плохо читается по сравнению с вызовом `.year`)

2024-05-08 14:12 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                    publication["title"][0],
у публикации несколько тайтлов?

2024-05-09 08:33 UTC, azzzile commented on app/domain/usecases/__init__.py
> +                    publication["title"][0],
да, может быть несколько , приходит в виде списка строк

2024-05-09 08:34 UTC, azzzile commented on app/domain/usecases/__init__.py
> +                    list(publication["author"]),
нет, приходит нампаевский массив просто)))

2024-05-09 08:36 UTC, azzzile commented on app/domain/usecases/__init__.py
> +                    int(publication["pubdate"][:4]),
ок!! поправлю

2024-05-09 09:06 UTC, azzzile commented on app/domain/usecases/__init__.py
> +                publication = ads_client.query_simple(f'bibcode:"{r.bibcode}"')[0]
я так не смогу, потому что сам адс рейзит ошибку, если нет результатов, а не просто отдает пустой запрос

2024-05-09 09:16 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                publication = ads_client.query_simple(f'bibcode:"{r.bibcode}"')[0]
А, окей
Тогда лучше будет в try-except блок обернуть только реально ту строчку, которая может ошибку дать, там у тебя выше три строки только не дадут никакой ошибки
try-except немного уменьшают производительность, поэтому лучше в них держать наименьшее число строк (да и читаться получше будет)

2024-05-09 09:17 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                    list(publication["author"]),
А, вижу, author это массив, тогда норм
Я подумал что там только первый автор

2024-05-09 09:18 UTC, Kraysent commented on app/domain/usecases/__init__.py
> +                    publication["title"][0],
Ладно, пусть будет так тогда

2024-05-09 09:30 UTC, azzzile commented on app/domain/usecases/__init__.py
> +                    publication["title"][0],
хотя может и нет... пока не нашла статей с несколькими названиями

2024-05-13 16:52 UTC, Kraysent requested changes

2024-05-13 16:52 UTC, Kraysent commented on tests/integration/rawdata_table_test.py
>          bib_resp = self.actions.create_source(model.CreateSourceRequest("2024arXiv240411942F", "test", ["test"], 2020))
не забывай что тебе теперь не обязательно передавать ничего кроме бибкода)

2024-05-13 16:52 UTC, Kraysent commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
а вот тут наоборот можно сделать - проверить что без бибкода но со всем остальным норм записывается

2024-05-13 16:52 UTC, Kraysent commented on tests/integration/sources_test.py
>  import unittest
Ну и вообще в идеале у тебя нигде в тестах не должно остаться передачи в тестируемый метод одновременно и бибкода, и тайтала с автором и годом
Единственное исключение - тест на то что если передать и бибкод, и тайтл, то тайтл перезапишется тем что придёт из ADS, такой надо сделать

2024-05-13 16:54 UTC, Kraysent commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
и в ADS не ходит

2024-05-13 16:55 UTC, Kraysent commented
А ну ещё обзови PR как-то содержательно)

2024-05-13 16:56 UTC, azzzile commented on tests/integration/rawdata_table_test.py
>          bib_resp = self.actions.create_source(model.CreateSourceRequest("2024arXiv240411942F", "test", ["test"], 2020))
значит ли это, что я могу везде из всех аргументов оставить только бибкод?

2024-05-13 16:56 UTC, azzzile commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
а, мхм

2024-05-13 16:56 UTC, azzzile commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
а как определить тип записи для отдельного теста

2024-05-13 16:57 UTC, azzzile commented on tests/integration/sources_test.py
>  import unittest
мхммммммммммм окэй!

2024-05-14 07:41 UTC, Kraysent commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
Ну так ты же сама это в логике написала)
Если передан bibcode, то идём в ADS и забираем оттуда title, authors и year, игнорируя соответствующие значения которые переданы в метод
Если он не передан, то никуда не идём, а используем то что нам передали в метод

Вот в тестах цель - проверить оба этих варианта
Для этого у тебя в каких-то тестах должен передаваться только бибкод, в каких-то - только тайтл, авторы и год

2024-05-14 07:41 UTC, Kraysent commented on tests/integration/rawdata_table_test.py
>          bib_resp = self.actions.create_source(model.CreateSourceRequest("2024arXiv240411942F", "test", ["test"], 2020))
см https://github.com/HyperLEDA/db-app/pull/126#discussion_r1599534134

2024-05-14 08:42 UTC, azzzile commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
так а разве у меня есть какое то разделение для такого? у меня же все тесты не заточены на проверку отдельного способа задания параметров

разве для такого не нужно отдельно сделать еще тест? в плане отдельно проверка только по бибкоду, отдельно проверка по бибкоду не из адс

или я чего то не понимаю? просто разве осмысленно, например, во всех тестах "подтягивать" дату, а в каком то случайном на проверку создания нескольких ресурсов одновременно почему то выбрать другой способ?

2024-05-14 08:53 UTC, Kraysent commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
ну основная задача - проверять, что при разном наборе параметров у тебя код работает
если хочется сделать отдельными тестами, можно отдельными, это не принципиально

2024-05-14 11:34 UTC, azzzile commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
а, ну ладно тогда ок!

2024-05-14 11:38 UTC, azzzile commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
кстати, а подобную проверку не логичнее ли сделать sources_test?

раз уж это связано напрямую только с публикациями, а не в rawdate менять?

2024-05-14 11:45 UTC, Kraysent commented on tests/integration/rawdata_table_test.py
> +                    "bibcode": "2024arXiv240411942F",
да, всё описанное в sources_test.py надо)

2024-05-30 17:48 UTC, Kraysent approved these changes

2024-05-30 17:48 UTC, merged