Cross identification use case
HyperLEDA/db-app pull request #142
Opened 2024-05-22 10:06 UTC by d-makarov-d

Cross identification use case implementation and testing

2024-05-26 15:11 UTC, d-makarov-d commented
Benchmarks for coss identification of data, that is processed

NPoints|Method|Init time| init mem| time | mem
-|-|-|-|-|-
1000 | simple | 1.1842000276374165e-06 s | 520 B | 0.27270523269999103 s | 1591 B
5000 | simple | 9.747000149218366e-07 s | 696 B | 1.362887727999987 s | 1307 B
10000 | simple | 9.039000360644422e-07 s | 696 B | 2.6923894366999774 s | 1136 B
20000 | simple | 9.348000276077073e-07 s | 696 B | 5.2818602004999775 s | 908 B
50000 | simple | 8.591000550950412e-07 s | 696 B | 13.299184179299937 s | 794 B
100000 | simple | 8.72999953571707e-07 s | 696 B | 27.283664147299987 s | 851 B
1000 | KDTree | 0.1397985143000028 s | 2496 B | 0.009556023200002529 s | 648 B
5000 | KDTree | 0.6949047902999951 s | 1464 B | 0.04530520970000111 s | 568 B
10000 | KDTree | 1.3894745881999995 s | 1464 B | 0.09047014139999873 s | 568 B
20000 | KDTree | 2.7816018049999967 s | 1464 B | 0.18125534010000025 s | 4016 B
50000 | KDTree | 6.960445219999997 s | 1464 B | 0.4546720884000024 s | 568 B
100000 | KDTree | 13.979613529100003 s | 1464 B | 0.9161960672000078 s | 568 B
1000 | PG | 11.274797418999924 s | 18567385 B | 0.005886024500000531 s | 120333 B
5000 | PG | 55.569541023000056 s | 89302536 B | 0.010739802200009762 s | 118103 B
10000 | PG | 110.42040012199993 s | 177774177 B | 0.00846416809999937 s | 117268 B
20000 | PG | 220.46685503050003 s | 354711813 B | 0.012114291000034427 s | 123448 B
50000 | PG | 546.2332218040001 s | 889378979 B | 0.02070331210002223 s | 131182 B
100000 | PG | 1085.408270817 s | 1774076438 B | 0.03519281429998955 s | 134372 B

2024-05-26 15:12 UTC, d-makarov-d commented
Benchmarks fro currently processed data cross identification

NPoints|Method|Init time| init mem| time | mem
-|-|-|-|-|-
1000 | simple | 1.1842000276374165e-06 s | 520 B | 0.27270523269999103 s | 1591 B
5000 | simple | 9.747000149218366e-07 s | 696 B | 1.362887727999987 s | 1307 B
10000 | simple | 9.039000360644422e-07 s | 696 B | 2.6923894366999774 s | 1136 B
20000 | simple | 9.348000276077073e-07 s | 696 B | 5.2818602004999775 s | 908 B
50000 | simple | 8.591000550950412e-07 s | 696 B | 13.299184179299937 s | 794 B
100000 | simple | 8.72999953571707e-07 s | 696 B | 27.283664147299987 s | 851 B
1000 | KDTree | 0.1397985143000028 s | 2496 B | 0.009556023200002529 s | 648 B
5000 | KDTree | 0.6949047902999951 s | 1464 B | 0.04530520970000111 s | 568 B
10000 | KDTree | 1.3894745881999995 s | 1464 B | 0.09047014139999873 s | 568 B
20000 | KDTree | 2.7816018049999967 s | 1464 B | 0.18125534010000025 s | 4016 B
50000 | KDTree | 6.960445219999997 s | 1464 B | 0.4546720884000024 s | 568 B
100000 | KDTree | 13.979613529100003 s | 1464 B | 0.9161960672000078 s | 568 B
1000 | PG | 11.274797418999924 s | 18567385 B | 0.005886024500000531 s | 120333 B
5000 | PG | 55.569541023000056 s | 89302536 B | 0.010739802200009762 s | 118103 B
10000 | PG | 110.42040012199993 s | 177774177 B | 0.00846416809999937 s | 117268 B
20000 | PG | 220.46685503050003 s | 354711813 B | 0.012114291000034427 s | 123448 B
50000 | PG | 546.2332218040001 s | 889378979 B | 0.02070331210002223 s | 131182 B
100000 | PG | 1085.408270817 s | 1774076438 B | 0.03519281429998955 s | 134372 B

2024-06-23 13:01 UTC, d-makarov-d commented on tests/integration/download_vizier_table_test.py
Для версии numpy 2.0.0 пришлось поправить `np.NaN` -> `np.nan`, тк `np.NaN` deprecated

2024-06-23 13:02 UTC, d-makarov-d commented on tests/integration/download_vizier_table_test.py
> +        test_table.add_row(("M333", np.nan, 10))
eged

2024-07-09 07:18 UTC, Kraysent requested changes

2024-07-09 07:18 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +            )
Давай тут попробуем сделать с прицелом на расширяемость - нам в конце концов придётся добавить в кросс-идентификацию возможность идентификации по большому числу параметров, не только по имени и координатам, но, например, по типу объекта (галактика, звезда) и по всему остальному в теории тоже. Можно попробовать прямо сейчас упростить себе в дальнейшем жизнь, а то если мы потом будем делать функции `_name_and_coord_and_type_known` (и любые комбинации пар этих трёх), нам будет грустно, потому что число таких функций будет расти как N^2 от числа параметров)

Я тут концептуально вижу следующий алгоритм: у нас есть набор параметров, по которым мы кросс-идентифицируем (имя, координаты, тип объекта, красное смещение и тд). По каждому из этих параметров кросс-идентификация независимо может выявить, что либо объект новый, либо объект уже существует, либо случилась коллизия и однозначно определить, что это за объект нельзя. Эти все процессы независимы, их можно разбить по своим функциям и дальше работать просто как с массивом ответов этих функций - по какому именно параметру каждая из них кросс-идентифицировала, для алгоритма не важно. Потом, чтобы отдать результат, нужно будет как-то скомбинировать результаты всех этих функций. Строго говоря тут тоже могут быть разные алгоритмы, например один из этих:
- если по *большему* числу параметров утверждается, что это новый (или существующий) объект, считаем, что объект действительно новый (или существующий)
- можно каждому параметру дать какой-то вес и потом, если взвешенное среднее по всем параметрам считает, что объект новый (существующий), то принимаем это решение в качестве результата
- если хотя бы по одному параметру есть коллизия, то считаем, что коллизия

Сейчас параметров немного, поэтому как будто сейчас нам нужен последний вариант, но в целом это в любой момент может поменяться и нужно быть готовым написать новый алгоритм, так что часть по комбинированию результатов тоже должна быть достаточно изолирована

2024-07-09 07:18 UTC, Kraysent commented on app/domain/usecases/transformation_0_1_use_case.py
и вот это тоже можно сразу в экшны положить

2024-07-09 10:38 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
Лучше в ветке рефакторинга этим займусь, вместе со всем остальным. Чтоб не путаться

2024-07-09 10:39 UTC, d-makarov-d commented on app/domain/usecases/transformation_0_1_use_case.py
Тож в рефакторинге

2024-07-09 10:41 UTC, d-makarov-d commented on pyproject.toml
> +    "B027", # empty method without abstract decorator
Чтобы не заставлять имплементирвать пустой метод. Например `CrossIdSimultaneousDataProvider.clear` нужно имплементировать только в `PostgreSimultaneousDataProvider`, а в остальных реализациях - нет

2024-07-09 10:50 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +            )
Ну, не уверен, что результаты по каждому из параметров можно считать независимыми. Для каждого кейса немного свои заморочки. В коммите `6e7d9b855d0a8ed16d1e7fb9356d98b82fd804a9` там еще логики прилетело, в связи с именами, можешь глянуть. Пока мне кажется, что получится очень сложная логика обработки "массива ответов". В общем надо подумать как сделаь. Мб отдельную задачу открыть. Этот PR хотелось бы уже закрыть, и так он пол года уже висит)

2024-07-09 10:59 UTC, d-makarov-d commented on app/commands/runserver/config.py
> +    clients: ClientsConfig = field(default_factory=lambda: ClientsConfig(""))
Да, еще вот строчку поменял, а то ошибку кидал `dataclass`. Не сломает ниче надеюсь?

2024-07-09 17:00 UTC, Kraysent commented on app/commands/runserver/config.py
> +    clients: ClientsConfig = field(default_factory=lambda: ClientsConfig(""))
Я уже, видимо прото ветка давно отведена была)
https://github.com/HyperLEDA/db-app/blob/master/app/commands/runserver/config.py#L30

2024-07-10 10:09 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +default_r1 = 1.5 * u.arcsec  # inner radius
Ок. Мб надо будет потом такого рода константы вообще в отдельный конфиг вынести

2024-07-10 19:10 UTC, Kraysent commented on pyproject.toml
> +    "B027", # empty method without abstract decorator
Ну ладно

2024-07-10 19:25 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +            )
Мб я не оч объяснил. У тебя сейчас тут три логики:
1. если есть только координаты, тогда кроссматчим по координатам
2. если есть только имена, то кроссматчим по именам
3. если есть и то, и то, то кроссматчим по обоим и потом комбинируем результат

Я утверждаю, что пункты 1 и 2 - подмножество пункта 3. Тогда логику можно сделать более плоской и сделать три другие функции - обработка координат, обработка имён и комбинирование результатов. У тебя сейчас то же самое и происходит, просто из-за того что ты в третьей функции рассматриваешь и то, и то, у тебя получается в коде дублирование вызова функций на обработку координат и обработку имён. Я предлагаю сделать что-то в духе:

1. Если есть координаты, обработать координаты, отдать результат
2. Если есть имена, обработать имена, отдать результат
3. Скомбинировать один или два результата

У тебя сейчас пункт 3 уже есть, тут (пока что) не требуется новой логики никакой: https://github.com/HyperLEDA/db-app/pull/142/files#diff-598bfbc05eb09232ab981b905729954503d295e377b0a6153687f3f338605e18R138-R165. Просто давай конкретно его сделаем отдельной функцией, которая, если на вход пришли только результаты координат или результаты только имен, отдаёт просто то что пришло, а если пришло и то, и то, комбинирует по той логике которая у тебя сейчас есть. Тут совсем немного кода менять, просто переразложить по функциям тот код который уже есть.

Тогда у тебя в итоге останется только один вызов `_only_names_known` и `_only_coord_known` в начале

Плюс такого решения в том, что при добавлении, например, кросс-идентификации по типу объекта, нам придётся только 1) добавить функцию `_only_object_type_known` 2) поправить функцию комбинирования; и больше ничего. А в текущем решении придётся дополнительно сочинять три функции `_coords_and_objtype_known`, `_names_and_objtype_known` и `_names_objtype_coords_known`

2024-07-10 19:39 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +            )
Ок, переформатирую, в целом должно получше выглядеть. Хотя бы с точки зрения именования ф-й). Я почему сразу так не сделал - там вряд ли добавится параметр, по которому мы именно идентифицируем галактики (не представляю, что это может быть). Все остальные параметры, типа тип объекта, размер, форма - скорее помогут отсеять ложные срабатывания, идентифицировать галактики по ним не получится

2024-07-16 19:45 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +OUTER_RADIUS = 1.5 * u.arcsec  # default outer radius
Разные же должны быть?

2024-07-16 20:24 UTC, Kraysent requested changes

2024-07-16 20:24 UTC, Kraysent commented on app/lib/storage/postgres/postgres_storage.py
> +                cursor.executemany(query, params)
`executemany` очень медленный, см например https://stackoverflow.com/a/10147451

Я так понимаю он тебе нужен чтобы за раз вставить много строк, sql такое поддерживает прям из коробки: https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-insert-multiple-rows/

Можно так строкой собрать запрос, я уже так делаю например вот тут: https://github.com/HyperLEDA/db-app/blob/master/app/data/template.py#L48-L56

Шаблон страшноватый, но аналогично можно такой же у тебя сделать и в итоге слать один запрос вместо кучи как делает executemany (он просто в цикле запускает execute и делает кучу запросов к базе, насколько я понял).

Ну и функцию не придётся отдельную делать

2024-07-16 20:24 UTC, Kraysent commented on app/domain/cross_id_simultaneous_data_provider.py
> +    def _sph_dist(a: ICRS, b: ICRS) -> Angle:
Это кажется можно вынести в простую функцию, тут вроде ничего специфического для этого класса нет

2024-07-16 20:24 UTC, Kraysent commented on app/domain/usecases/transformation_0_1_use_case.py
> +            user_param = CrossIdentificationUserParam(None, None)
Такое вроде нельзя, здесь же гарантированно ошибка вернётся?

2024-07-16 20:24 UTC, Kraysent commented on app/domain/usecases/transformation_0_1_use_case.py
> +        for i, param in zip(list(range(n_rows)), identification_params):
`zip(list(range(n_rows)), identification_params)` можно поменять на `enumerate(identification_params)`

2024-07-16 20:24 UTC, Kraysent commented on app/domain/usecases/transformation_0_1_use_case.py
> +            if isinstance(param, BaseException):
Ну и тут тоже не делают так обычно) Тут явно нужно просто проверять что ошибка не None, Exception-ы не за это отвечают)

2024-07-16 20:24 UTC, Kraysent commented on app/domain/usecases/transformation_0_1_use_case.py
> +        # Simultaneous data provider needs only valid CrossIdentificationParam's
CrossIdentificationParams)

2024-07-17 05:31 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +OUTER_RADIUS = 1.5 * u.arcsec  # default outer radius
Блин, точно, поправил

2024-07-17 05:39 UTC, d-makarov-d commented on app/domain/cross_id_simultaneous_data_provider.py
> +    def _sph_dist(a: ICRS, b: ICRS) -> Angle:
В целом да, вынес

2024-07-17 05:40 UTC, d-makarov-d commented on app/domain/usecases/transformation_0_1_use_case.py
> +            user_param = CrossIdentificationUserParam(None, None)
Нет, будут исполльзованы значения по умолчанию `INNER_RADIUS`, `OUTER_RADIUS`

2024-07-17 05:55 UTC, d-makarov-d commented on app/lib/storage/postgres/postgres_storage.py
> +                cursor.executemany(query, params)
Я, собственно, сначала и собирал одной строкой. Но когда заливал много строк, вылезло посгресовское ограничение на длину строки в 65k символов. По этому и сделал executemany. Вроде в более новых версиях либы он уже не столь медленный. По крайней мере не столь медленный, как если отдельно каждую строчку пихать)

2024-07-17 05:57 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +        if isinstance(names_res, result.CrossIdentifySuccess) and isinstance(coord_res, result.CrossIdentifySuccess):
Ну эт кому как)

2024-07-17 06:00 UTC, d-makarov-d commented
По возвращаемым эксепшенам - это в отдельную ищью, либо к рефакторингу добавить. Потому что это у меня тянется много откуда, соответственно кучу кода надо менять

2024-07-17 06:02 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +    async def invoke(
Привычка с котлина, все IO и тяжелое в асинхронные ф-и оборачивать. Оно ж не мешает?

2024-07-17 06:03 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +    ) -> result.CrossIdentifySuccess | result.CrossIdentificationException:
По возврату эксепшенов в отдельном комменте написал https://github.com/HyperLEDA/db-app/pull/142#issuecomment-2232489399

2024-07-17 06:05 UTC, Kraysent commented
> По возвращаемым эксепшенам - это в отдельную ищью, либо к рефакторингу добавить. Потому что это у меня тянется много откуда, соответственно кучу кода надо менять

Ну я не имею ввиду сразу везде менять, но по крайней мере в коде, который меняется в этом ПРе, можно сразу поменять, сам же себе потом работу облегчишь:
- https://github.com/HyperLEDA/db-app/pull/142/files#diff-598bfbc05eb09232ab981b905729954503d295e377b0a6153687f3f338605e18R65
- https://github.com/HyperLEDA/db-app/pull/142/files#diff-598bfbc05eb09232ab981b905729954503d295e377b0a6153687f3f338605e18R97

Вот эти функции например и создаются, и используются только в новом коде, тут сразу же можно сделать правильное возвращающее значение

- https://github.com/HyperLEDA/db-app/pull/142/files#diff-598bfbc05eb09232ab981b905729954503d295e377b0a6153687f3f338605e18R29

Вот это возвращаемое значение тоже используется только в новом коде, можно сразу сделать правильно

2024-07-17 06:08 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +    async def invoke(
Ну оно мешает в плане что создаёт лишний код, который не используется и сбивает при чтении
Ну и кроме того оно тайпинги меняет под капотом - в сигнатуре написано что оно возвращает `result.CrossIdentifySuccess | result.CrossIdentificationException`, а оно на самом деле возвращает `Awaitable[result.CrossIdentifySuccess | result.CrossIdentificationException]`

Ну и вызвать функцию без await нельзя

ну крч я бы помечал функции асинхронными только когда это непосредственно надо, пока что как будто нет необходимости

2024-07-17 06:11 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +    ) -> result.CrossIdentifySuccess | result.CrossIdentificationException | None:
Вынес проверку на наличие инфы наверх, осталось `result.CrossIdentifySuccess | result.CrossIdentificationException`. По невозвращению эксепшена чуть ниже

2024-07-17 06:14 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +        if isinstance(names_res, result.CrossIdentifySuccess) and isinstance(coord_res, result.CrossIdentifySuccess):
Да ну нет же)
Проверка на равенство ошибки None выглядит гораздо читаемее, чем проверка объекта на тип, None же ровно для такого и существует - если значение есть, сделать одно, если нет - другое

Неужели тебе правда кажется что
```python
if names_res.error is not None
```

выглядит менее читаемо, чем 
```python
if isinstance(names_res, result.CrossIdentificationException)
```
?

2024-07-17 06:17 UTC, d-makarov-d commented
Ну в целом то надо во всем коде поменять) Потому что если сейчас быстро могу только `Optional` на `dataclass` поменять, но от этого эксепшены не перестанут возвращаться

2024-07-17 06:18 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +        if param.coordinates is None:
Вынес

2024-07-17 06:19 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +        param: CrossIdentificationParam,
Весь `param` в ошибку как аргумнт передается

2024-07-17 06:21 UTC, Kraysent commented on app/lib/storage/postgres/postgres_storage.py
> +                cursor.executemany(query, params)
А сколько у тебя символов запросы выходят? Там вся таблица за раз лежит?

2024-07-17 06:29 UTC, Kraysent commented
> Ну в целом то надо во всем коде поменять) Потому что если сейчас быстро могу только Optional на dataclass поменять, но от этого эксепшены не перестанут возвращаться

Ну сейчас у тебя как будто не много надо сделать
- [Вот сюда](https://github.com/HyperLEDA/db-app/pull/142/files#diff-06d9151e2dabc84d0b64ba419a081d140afe489f0a5fe52c53e93344501a951fR5-R10) добавить поле error, куда положить те же самые ошибки, которые ты сейчас возвращаешь (и мб сам класс переименовать в Result вместо Success)
- [Вот тут](https://github.com/HyperLEDA/db-app/pull/142/files#diff-598bfbc05eb09232ab981b905729954503d295e377b0a6153687f3f338605e18R140) начать проверять на `res.error is None` вместо `isinstance`
- И [вот тут](https://github.com/HyperLEDA/db-app/pull/142/files#diff-d6d6afc7a25aa92033702043e81ecbd1fc7af8b712caa652a998bbb4d5d78bedR107-R115) начать проверять на поле error вместо isinstance

Да и вроде всё, всё остальное без этого сработает, всё остальное можно поменять уже отдельно

2024-07-17 06:33 UTC, d-makarov-d commented
Вообще мне `Union` больше нравится чем `dataclass`. Он однозначней, либо то, либо другое. А в такой `Result` формально можно например два `None` запихнуть

2024-07-17 06:39 UTC, d-makarov-d commented
Или это некая стандартная практика для питона? Таким образом результат оформлять?

2024-07-17 08:05 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +OUTER_RADIUS = 1.5 * u.arcsec  # default outer radius
Подумал что можно даже просто переименовать в DEFAULT_INNER_RADIUS, тогда комменты не нужны будут

2024-07-17 08:37 UTC, d-makarov-d commented on app/lib/storage/postgres/postgres_storage.py
> +                cursor.executemany(query, params)
Ну прям символы не считал, но когда зараз пытался запихнуть таблицу на несколько тысяч строк с 4-мя столбцами, начинал выходить за лимиты. Можно попробовать батчами несколько строк пихать через `executemany`, но там ведь еще от кол-ва колонок будет сильно зависеть, сколько строк можем зараз залить

2024-07-17 08:38 UTC, Kraysent commented
> Или это некая стандартная практика для питона? Таким образом результат оформлять?

Ну смотри, ответ на две части разобью

1. Стандартная практика для питона - рейзить ошибки, а не возвращать (как и для кучи других языков, включая джаву и котлин, кажется).

    Тогда код можно переписать в виде

    ```python
    async def invoke(
        self,
        param: CrossIdentificationParam,
        simultaneous_data_provider: CrossIdSimultaneousDataProvider,
        user_param: CrossIdentificationUserParam,
    ) -> result.CrossIdentifySuccess:
      if param.names is None and param.coordinates is None:
          raise result.CrossIdentificationEmptyException()
      ....
    
      return res
    ```

    и получится норм с точки зрения практики питона.

2. Следующее утверждение, уже связанное не конкретно с питоном, а в целом с использованием функции - бросание ошибок, как выше, усложняет читаемость функции, потому что по сигнатуре функции `def invoke(self, CrossIdentificationParam, CrossIdSimultaneousDataProvider, CrossIdentificationUserParam) -> result.CrossIdentifySuccess` непонятно, какие ошибки она бросает, и соответственно чтобы пользователь функции мог понять, как ей пользоваться, ему нужно залезать в реализацию функции и просмотреть код функции на предмет возможных ошибок. Это часто ведёт к ошибкам из-за человеческого фактора - читатель может не увидеть один из возможных видов ошибок, или, например, при изменении логики добавим новый вид ошибок и забудем поменять во всех местах пользования.

     Поэтому мне тут кажется более правильным возвращать структуру, которая в себе хранит ошибку, которая может быть None. Это не обязательно может быть `dataclass`, можно сделать, например, tuple:
    ```python
    async def invoke(
        self,
        param: CrossIdentificationParam,
        simultaneous_data_provider: CrossIdSimultaneousDataProvider,
        user_param: CrossIdentificationUserParam,
    ) -> tuple[result.CrossIdentifySuccess | None, CrossIdentificationError | None]:
      if param.names is None and param.coordinates is None:
          return None, CrossIdentificationEmptyError
      ....
    
      return res, None
    ```

    И тогда в месте использования будет что-то типа
    ```python
      result, err = CrossIdentifyUseCase().invoke(.....)
      if err is not None:
        'возвращаем ошибку'
      
      'работаем с результатом'
    ```

    Если не нравится, что они могут оба быть None, можешь сделать результат классом, в конструкторе которого принимается два аргумента, один из которых обязан быть не None, тогда у тебя будет гарантия что никто не сможет собрать инстанс класса в котором оба параметра None.

2024-07-17 08:42 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +    async def invoke(
Ну я не имею ввиду здесь убрать сразу всё из всего проекта)
Можно тут в новых функциях убрать, зачем коммитить код, который сразу после этого собираешься рефакторить?

2024-07-17 08:49 UTC, d-makarov-d commented
С первой частью я и не спорил, тут мой косяк, это да, везде плохая практика

Со второй частью не совсем согласен, в плане возможных ошибок - как раз в типе указано, что может быть только `CrossIdentificationException` и все ее подклассы. И собственно, раницы мажду `Union` или `tuple` или `dataclass` с типизацией принципиальной нет.

А в целом, если тебе прям режет глаз, без б, закоммичу вариант с классом и проверкой в конструкторе. Более того, я уже зарефакторил на класс `Result`, но на мой взгляд, лучше не стало)

2024-07-17 08:54 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +    async def invoke(
Да там же и у репозиториев все `async`, соответственно с них надо будет убирать, а там со всех ф-й, которые вызывают репозитории... Короче так и так весь дофига кода затронет

2024-07-17 08:57 UTC, Kraysent commented
> Со второй частью не совсем согласен, в плане возможных ошибок - как раз в типе указано, что может быть только CrossIdentificationException и все ее подклассы. И собственно, раницы мажду Union или tuple или dataclass с типизацией принципиальной нет.
> 
> А в целом, если тебе прям режет глаз, без б, закоммичу вариант с классом и проверкой в конструкторе. Более того, я уже зарефакторил на класс Result, но на мой взгляд, лучше не стало)

Ну я имею ввиду, что если поменять код в соответствии с первой частью, то получится, что ошибки начнут скрываться - возвращаемое значение останется только одно. Я собственно и предлагаю делать не одно возвращаемое значение, а два, примерно как у тебя сейчас)

Между Union и Tuple разница в том, что в union можно забыть проверить на разные типы, а с tuple забыть точно не получится, потому что возвращаемых значений *всегда* два

2024-07-17 09:03 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +    async def invoke(
Ну вот тут например явно же ничего не затронет: https://github.com/HyperLEDA/db-app/pull/142/files#diff-598bfbc05eb09232ab981b905729954503d295e377b0a6153687f3f338605e18R65

Тут можно просто убрать async и в месте использования убрать await: https://github.com/HyperLEDA/db-app/pull/142/files#diff-598bfbc05eb09232ab981b905729954503d295e377b0a6153687f3f338605e18R52

Или я что-то упускаю?

Ну и то же самое сделать для _identify_by_names и для invoke класса CrossIdentifyUseCase

кроме этих трех вроде как больше нигде не надо, у тебя получатся вот эти функции простыми синхронными функциями

2024-07-17 09:09 UTC, Kraysent commented on app/lib/storage/postgres/postgres_storage.py
> +                cursor.executemany(query, params)
Меня тут смущает, что если у тебя таблица на миллионы строк (любой каталог SDSS или старая БД Леды, например), то ты весь миллион попытаешься отправить текстом по сети за раз в базу данных (а это гигабайты данных), это не оч хорошая практика, потому что соединение может прерываться и в целом у тебя поток зависает, пока загружает эти данные. Тут как будто можно тоже батчами загружать по несколько тысяч объектов

Я кстати не нашёл про 65к инфу, вот тут пишут что до двух миллиардов можно: https://stackoverflow.com/a/4937695

2024-07-17 09:10 UTC, Kraysent commented on app/domain/model/params/cross_dentification_user_param.py
файлик называется cross_dentification

2024-07-17 09:15 UTC, Kraysent commented on app/domain/usecases/transformation_0_1_use_case.py
> +            user_param = CrossIdentificationUserParam(None, None)
А, ок, не туда посмотрел

2024-07-17 09:23 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +    async def invoke(
Уберу `async`, где не затронет дофига зависимостей

2024-07-17 09:25 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +        param: CrossIdentificationParam,
Ок, сделаю эксепшены более конкретными

2024-07-17 09:32 UTC, d-makarov-d commented on app/lib/storage/postgres/postgres_storage.py
> +                cursor.executemany(query, params)
Ну насчёт батчей пока реализации нет, а вот ошибка на 65k знаков есть. Да и таблица на несколько тыщ строк не так уж много. Мб про 65k где то в конфигах можно изменить, не знаю. Ошибку могу повторить, мне не сложно) подумаем, что с ней делать

2024-07-17 09:38 UTC, d-makarov-d commented on app/domain/model/params/cross_identification_param.py
> +    names: Optional[list[str]]
Ок

2024-07-17 09:39 UTC, d-makarov-d commented on app/domain/model/params/cross_dentification_user_param.py
??

2024-07-17 09:50 UTC, d-makarov-d commented
Так, ладно, по итогам дебатов. А то я уже в этих ветках потерялся.

- по `async` выпиливаю здесь, где могу, остальное в issue
- по возвращению эксепшенов - перехожу на возвращение класса из юзкейса, остальное в issue 
- делаю эксепшены более специальными, чтобы не передавать `param`
- мелкие правки по стилю
- по `executemany` - отдельная ишью, где повторяю ошибку и решаем, че с ней делать

Все так, ничего не забыл?

2024-07-17 10:21 UTC, Kraysent commented on app/domain/model/params/cross_dentification_user_param.py
ну опечатка) i забыл

2024-07-17 10:22 UTC, Kraysent commented
> Так, ладно, по итогам дебатов. А то я уже в этих ветках потерялся.
> 
> * по `async` выпиливаю здесь, где могу, остальное в issue
> * по возвращению эксепшенов - перехожу на возвращение класса из юзкейса, остальное в issue
> * делаю эксепшены более специальными, чтобы не передавать `param`
> * мелкие правки по стилю
> * по `executemany` - отдельная ишью, где повторяю ошибку и решаем, че с ней делать
> 
> Все так, ничего не забыл?

Вроде норм

2024-07-17 14:32 UTC, d-makarov-d commented on app/domain/model/params/cross_dentification_user_param.py
А, ахах) В упор не вижу) фига у тебя глаз наметан))

2024-07-26 12:07 UTC, d-makarov-d commented
- Изменения запушил
- Удаление `async` добавил к ишью рефакторинга https://github.com/HyperLEDA/db-app/issues/167
- По возвращению эксепшенов https://github.com/HyperLEDA/db-app/issues/181
- По `executemany` https://github.com/HyperLEDA/db-app/issues/182

2024-07-31 19:01 UTC, Kraysent requested changes

2024-07-31 19:02 UTC, Kraysent commented on app/domain/usecases/transformation_0_1_use_case.py
> +            if isinstance(param, BaseException):
А тут не получилось без масштабных изменений поменять?

2024-07-31 19:06 UTC, Kraysent requested changes

2024-07-31 19:06 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +INNER_RADIUS = 1.5 * u.arcsec  # default inner radius
тоже DEFAULT_..... вроде хотели)

https://github.com/HyperLEDA/db-app/pull/142#discussion_r1679986275

2024-07-31 19:52 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +INNER_RADIUS = 1.5 * u.arcsec  # default inner radius
Переименовал

2024-07-31 19:56 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +        :param r2: Outer radius
Комменты никогда лишними не будут) переименовал

2024-07-31 19:57 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +            return result.CrossIdentifyResult(None, result.CrossIdentificationNamesNotFoundException(names))
Это в рефакторинге уйдет

2024-07-31 19:59 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +        :return: UseCase result
Ну как задел на будущие комменты. Лучше вообще ничего не писать что ли?

2024-07-31 20:00 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +            return coord_res
Не из этой.

2024-07-31 20:03 UTC, d-makarov-d commented on app/domain/usecases/cross_identify_use_case.py
> +            return coord_res
В ответственность этой ф-и входит валидация результатов работы предидущих ф-й, даже в названии обозначено

2024-07-31 20:05 UTC, d-makarov-d commented on app/domain/model/params/cross_identification_result.py
> +        self.db_cross_id_result: CrossIdentifyResult | CrossIdentificationCoordCollisionException = db_cross_id_result
Учтем в рефакторинге, и переименуем, и от наследования от `BaseException` избавимся

2024-07-31 20:05 UTC, d-makarov-d commented on app/domain/model/params/cross_identification_result.py
> +        self.coord_hit = coord_hit
Учтем в рефакторинге, и переименуем, и от наследования от `BaseException` избавимся

2024-07-31 20:12 UTC, d-makarov-d commented on app/domain/model/params/__init__.py
> +        return self.name
Да пережитки ООП-прошлого, ес честно) Тут этот метод можно выпилить, по факту. А обращение через вызов метода, или через точку - разницы нет, кому как по кайфу

2024-07-31 20:22 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +            return coord_res
Ну просто если одного из результатов нет, то и компилировать нечего)

2024-07-31 20:23 UTC, Kraysent commented on app/domain/usecases/cross_identify_use_case.py
> +        :return: UseCase result
Ну хз, не вижу особого смысла в комментах, которые ничего не говорят, это же просто лишний текст)
Ну ладно, фиг с ним в целом

2024-07-31 20:24 UTC, Kraysent commented on app/domain/model/params/__init__.py
> +        return self.name
Ну опять же, лишний код, который нужно поддерживать

2024-07-31 20:25 UTC, Kraysent commented on app/domain/model/params/cross_identification_result.py
> +        self.coord_hit = coord_hit
А, тут же наследование, ладно

2024-07-31 20:49 UTC, Kraysent approved these changes

2024-07-31 21:51 UTC, merged